export class CountryNotFoundError {}
export class ResourceNotFoundError {}
export class InsufficientResourceFromSellerError {}
export class InsufficientResourceFromBuyerError {}
export class NoPriceEstablishedError {}
export class BuyerResourceNotFoundError {}
export class SellerResourceNotFoundError {}
export class BuyerCountryNotFoundError {}
export class SellerCountryNotFoundError {}